In [1]:
import tensorflow as tf

# Define hyperparameters
filters = 1  # Number of output filters (feature maps)
kernel_size = (3, 3)  # Size of the convolution kernel
strides = (1, 1)  # Stride of the convolution
padding = "VALID"  # Padding method (to maintain output size)
dilation_rate = (1, 1)  # Dilation rate (controls spacing between kernel elements)

# Create random input with multiple channels
batch_size = 1  # We'll process a single image
input_height = 5  # Example height
input_width = 5  # Example width
input_channels = 3  # Number of input channels (e.g., RGB)
input_tensor = tf.random.normal(shape=(batch_size, input_height, input_width, input_channels))
print(input_tensor)

# Define the convolution layer
conv_layer = tf.keras.layers.Conv2D(
    filters=filters,
    kernel_size=kernel_size,
    strides=strides,
    padding=padding,
    dilation_rate=dilation_rate,
    groups=1,
    activation= None,  # Optional activation function (e.g., ReLU)
    use_bias = None
)

# Build the layer to initialize its weights
conv_layer.build(input_shape=(batch_size, input_height, input_width, input_channels))


# Get the kernel weights
kernel_weights = conv_layer.get_weights()[0]

# Print the kernel weights
print("Kernel Weights:")
print(kernel_weights)


# Apply the convolution
output_tensor = conv_layer(input_tensor)

# Print the input shape
print("Input shape:", input_tensor.shape)

# Print the kernel size
print("Kernel size:", conv_layer.kernel.shape)

# Print the output shape (for verification)
print("Output shape:", output_tensor.shape)

print(output_tensor)


tf.Tensor(
[[[[ 1.7204162  -0.05881087 -0.04916574]
   [ 0.29207978 -0.23069172 -1.5687047 ]
   [-0.56805533 -0.93757397  0.40958712]
   [ 0.77343136  0.13873123  1.0200988 ]
   [-0.7784866  -1.8380507   0.32969496]]

  [[ 0.6466695  -1.7378098  -0.33046344]
   [-0.8800376  -0.46294898 -1.1823705 ]
   [ 0.3731629  -1.8532      0.99535   ]
   [-0.54533273  0.48403525 -0.8318747 ]
   [-0.5027658  -1.3754635   0.6533206 ]]

  [[-1.0442113  -0.00802162  0.72869694]
   [ 0.03407151  0.12831567 -1.4093165 ]
   [ 0.330889   -1.7824847  -0.6249094 ]
   [-0.15900038  1.1879401   2.4161918 ]
   [-0.52975196  0.03461237 -1.0350772 ]]

  [[ 2.445415    1.2544405   0.9621104 ]
   [-0.8949387  -0.06073615  0.5365606 ]
   [ 0.50455874 -1.5503237  -0.98184586]
   [-1.4269677   0.7955299  -1.3490329 ]
   [ 0.0814769   1.4192054  -1.2987328 ]]

  [[-3.3858132  -0.24233125  0.7859153 ]
   [-1.3394349  -0.16732603 -1.4944209 ]
   [ 1.4313493  -0.7424999   0.15199016]
   [ 0.01224616 -1.9886144  -1.6876745