In [ ]:
import tensorflow as tf

# Define input shape
input_shape = (1, 2, 2, 1)  # Replace with desired dimensions

# Generate random input with multiple channels
random_input = tf.random.normal(shape=input_shape)
print(random_input)

# Define kernel size and number of output channels
kernel_size = (2, 2)  # Adjust kernel size as needed
num_filters = 1  # Adjust number of output filters

# Define transposed convolution layer
transpose_conv = tf.keras.layers.Conv2DTranspose(
    filters=num_filters,
    kernel_size=kernel_size,
    strides=(1, 1),  # Stride of 1
    padding="valid",  # Padding of 1 (same padding)
    dilation_rate=(1, 1),  # Dilation rate of 1
    activation=None,  # Apply ReLU activation (optional)
    input_shape=input_shape
)

# Call build method to initialize the weights
transpose_conv.build(input_shape)

# Print the kernel
print("Kernel:")
print(transpose_conv.kernel)

# Apply transposed convolution to the input
output = transpose_conv(random_input)


print("Input shape:", input_shape)

# Print the kernel size
print("Kernel size:", transpose_conv.kernel.shape)

# Print the output shape
print(f"Output shape: {output.shape}")

print(output)



tf.Tensor(
[[[[-0.7974513 ]
   [-0.32529014]]

  [[ 1.6374652 ]
   [ 0.5086184 ]]]], shape=(1, 2, 2, 1), dtype=float32)
Kernel:
<tf.Variable 'kernel:0' shape=(2, 2, 1, 1) dtype=float32, numpy=
array([[[[ 0.10195458]],

        [[-0.24636489]]],


       [[[-0.65866494]],

        [[ 0.74693865]]]], dtype=float32)>
Input shape: (1, 2, 2, 1)
Kernel size: (2, 2, 1, 1)
Output shape: (1, 3, 3, 1)
tf.Tensor(
[[[[-0.08130381]
   [ 0.16329917]
   [ 0.08014007]]

  [[ 0.6922003 ]
   [-0.732948  ]
   [-0.3682775 ]]

  [[-1.0785409 ]
   [ 0.888077  ]
   [ 0.37990674]]]], shape=(1, 3, 3, 1), dtype=float32)
